### ISSUE TITLE
Error popup on startup

### ISSUE THREAD

**Issue by teetteet** [leadedge/SpoutCapture#1]
Hello,
on Windows7 x64 i get an error popup: "Desktop duplication interface creation failed". The sender is recognized by the receiver. No Mode e.g. GPU or CPU sharing is sending no video.

**Comment by leadedge** [comment]
Sorry to say that the desktop duplication method is not available for Windows 7. In the interests of simplicity I don't have any checks for it.

**Comment by leadedge** [comment]
But according to this -

https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgioutput1-duplicateoutput

you might get somewhere with this -

https://docs.microsoft.com/en-us/windows/win32/direct3darticles/platform-update-for-windows-7

**Comment by teetteet** [comment]
Thanks for the links but i am unable to install this version. I also saw that different programs bundle these sets for older OSes like win7? Spout unable to work on my win7 setup would be really sad because its essential. Maybe there will be a future idea how to hold on win7 by any chance.

**Comment by leadedge** [comment]
OK I thought it might help. But the links refer only to the desktop duplication method. Spout itself should still work OK with Win 7.

I have not got a Windows 7 system any more and have not tested it for a while. Please run the demo sender and receiver to see if it works OK and let me know.

The only way I can confidently support Windows 7 for screen capture is to use the GDI method for capturing the screen, but I have found that it is too slow. This program aims for systems with Windows 8 and 10.

**Comment by teetteet** [comment]
I can confirm that demo sender and receiver working perfect in every mode on win7 x64. The last Shadertoysender seems also not to work anymore on win7 x64 as of the last release.

**Comment by leadedge** [comment]
OK thanks a lot. At least Spout itself still works. ShaderToySender has been extensively revised for Resolume 7 and OpenGL 4. Windows 7 has never been tested. I need to know whether your problem is with saving plugins or just Spout output. What is the exact problem.

**Comment by teetteet** [comment]
ShaderToySender 2.008c also fails to start at all and just crashes and aksing for some dll named "api-ms-win-shcore-scaling-l1-1-1" is missing. Cant add it in from myside, there are various dependencies not found on win7. Last working version for me is v2.005 and i have no problem with saving or spout output and have it running at ~ 60 FPS.

**Comment by leadedge** [comment]
I traced this back to adding a call to "SetProcessDpiAwareness" that requires Shcore.lib. DPI awareness is necessary due to blurry text if scaling is used for the display for Windows 10. I could not get the manifest setting to work with this program for some reason.

However, I can replace it with "SetProcessDpiAwarenessContext" which requires User32.lib and seems to work OK. I can send you a copy to test if you contact me using the email contact on the Spout home page.

For screen capture with Windows 7 the only way is to use GDI methods. This project might suit your requirements.

https://github.com/spiraltechnica/ScreenShare

**Comment by teetteet** [comment]
Thanks for your hard work! So glad that win7 is still doable! Keep up the good work!

**Comment by leadedge** [comment]
I think the alternative dpi function should resolve that one.

For this project, it is possible to detect Windows 7 and activate GDI methods, but I ran some timing tests and the best I can get is 19fps for full screen capture. The only practical way to use GDI is to capture individual windows, but that changes the whole program design. Hooking DirectX or OpenGL is the only other way I know of. It's not easy though and again you need a completely different program.
