### ISSUE TITLE
Multiple Display bug

### ISSUE THREAD

**Issue by magadan** [leadedge/SpoutCapture#2]
Hello, i have 3 displays (monitors), SpoutCapture only works on main display. Will be nice if is possible to work with another displays or selecting a Application Window.

**Comment by leadedge** [comment]
This is not a bug but rather a decision to support only the primary monitor. Although I did think about it. If you look at line 189 and follow the reference link you can see how it might be done. \
As for capturing windows, there are two ways to do it, the fast way and the slow way. The fast way uses a rather complicated method of hooking DirectX. I tried but failed to understand it. The slow way is to use windows GDI CPU methods. I found that it wasn't fast enough although it remains a possibility for smaller window sizes.\
Meanwhile, if you have not done so already, it's worth looking at NDI Scan Converter and OBS Studio which has a very nice game capture function. These might have multiple monitor capability.

**Comment by magadan** [comment]
Thanks @leadedge.
