### ISSUE TITLE
Capture will be stopped when application is minimised?

### ISSUE THREAD

**Issue by vkedwardli** [leadedge/SpoutCapture#3]

**Comment by leadedge** [comment]
All three capture methods, desktop, region or window continue if SpoutCapture is minimised. The speed of window capture is improved slightly.

**Comment by leadedge** [comment]
I have updated the readme to clarify this. More details are in the Release pdf. Please feel free to join the [Spout Discourse group](https://spout.discourse.group/) if you have any further questions.

**Comment by vkedwardli** [comment]
![image](https://user-images.githubusercontent.com/602245/137995000-0e3e5d30-a3a1-4b43-bccf-01a5597313e7.png)

I'm testing on a newly installed Windows machine, but the capture will be stuck if I minimize the program for a certain period of time

**Comment by leadedge** [comment]
I have run full screen capture when minimized for over 2 hours with no trouble. How long is the period of time you mention?

I assume that this is still a Windows 10 machine. I haven't explored Windows 12 yet.

What is the graphics card and driver version?

Turn Sleep off completely to find out if that's an issue.
