### ISSUE TITLE
Command Line Interface

### ISSUE THREAD

**Issue by RomainKurtz** [leadedge/SpoutCapture#5]
Is it possible to launch the capture of a window of an application with a command line ?

Thank you, for this usefull app.
Kind regards

**Comment by leadedge** [comment]
Yes I think that could be done. This project should be updated anyway and I could look at possibilities then. Do you have something in mind for this?

**Comment by RomainKurtz** [comment]
Probably something like the gdigrab function of ffmpeg : https://ffmpeg.org/ffmpeg-devices.html#gdigrab
The most important thing for me is to grab a window with its name.

**Comment by leadedge** [comment]
OK, I understand. I will look at updating the project for VS2022 and find out what is involved.

**Comment by leadedge** [comment]
Well there's good news and bad news.

The command line interface works OK and the requested window is captured. But this disables the mouse hook for some reason and you can't select another window.

The program is too complicated to find out how to resolve this, and I don't want to add something that doesn't work properly, so I made a stripped back version just to capture a window and that works fine. 

The application is minimised so it only appears on the taskbar. You can't capture another one with that application, but you can start another instance with a new batch file and you get "Windows Sender_1", "Windows Sender _2" etc. Each can be closed independently.

If this works for you I will create a branch for it.

**Comment by RomainKurtz** [comment]
Wonderful, this would be perfect for me !

Thank you very much.

**Comment by leadedge** [comment]
OK. I should have some time next week.

**Comment by leadedge** [comment]
I had some time this weekend and created a "command-line" branch. Let me know how you go with this.

**Comment by RomainKurtz** [comment]
This is exactly what I wanted, thank you very much !

**Comment by leadedge** [comment]
I am glad this works for you. It's very simple and a useful addition.
